### ISSUE TITLE
Basic Energies from PTCGL exports do not combine

### ISSUE THREAD

**Issue by generalraikou** [BAA-Studios/CastFORM#11]
Okay, I think this is last attempt at fuzzing the decklist parser for bugs tonight:

I imagine like-basic energy cards, whether secret rares, or not, should be combined.  Below is an example export from PTCGL that has two scenarios of basic energy that should be combined:

1. Two basic grass secret energies, one from Fusion Strike, and one from Paldea Evolved.
2. Two basic lightning energies - one completely basic, one secret.

Decklist:
Pokémon: 10
1 Regieleki VMAX SIT 58
2 Regieleki V SIT 57
1 Zeraora SIT 56
3 Pachirisu SVI 68
1 Ting-Lu ex PAL 263
1 Pikachu PR-SV 27
1 Cyclizar ex PR-SV 18
1 Bombirdier SVI 219
1 Pelipper PAL 159
1 Pelipper PR-SV 22

Trainer: 17
2 Ultra Ball SVI 196
1 Boss's Orders PAL 265
1 Boss's Orders PAL 248
4 Professor's Research SVI 190
2 Escape Rope BST 125
1 Energy Recycler BST 124
4 Nest Ball SVI 181
3 Leafy Camo Poncho SIT 160
4 Electric Generator SVI 170
3 Beach Court SVI 167
2 Cynthia's Ambition BRS 138
1 Iono PAL 185 PH
1 Iono PAL 269
1 Iono PAL 254
1 Giacomo PAL 182
1 Giacomo PAL 267
1 Giacomo PAL 252

Energy: 4
11 Basic {L} Energy SVE 4
1 Basic {G} Energy FST 283
1 Basic {G} Energy PAL 278
1 Basic {L} Energy SVI 257

Total Cards: 60

Screenshot:
![secret energy not combined](https://github.com/BAA-Studios/CastFORM/assets/140216247/ebff4ad9-32ec-43dd-a48c-81e36c7061f4)

**Comment by generalraikou** [comment]
Actually, this is a better fuzzing case.  Take every possible basic lightning energy available in PTCGL, put it in a deck, export list, and see what combines.  None of them.  

Decklist:
Pokémon: 5
1 Pikachu PR-SV 27
3 Pachirisu SVI 68
1 Regieleki VMAX SIT 58
2 Regieleki V SIT 57
1 Zeraora SIT 56

Trainer: 15
1 Ultra Ball SVI 196
1 Giacomo PAL 267
4 Professor's Research SVI 190
1 Boss's Orders PAL 265
2 Escape Rope BST 125
1 Energy Recycler BST 124
4 Electric Generator SVI 170
1 Iono PAL 269
1 Giacomo PAL 182
1 Boss's Orders PAL 248
1 Iono PAL 185 PH
3 Leafy Camo Poncho SIT 160
1 Iono PAL 254
1 Giacomo PAL 252
1 Boss's Orders PAL 172 PH

Energy: 25
1 Basic {L} Energy SVI 257
1 Basic {L} Energy Energy 30 PH
4 Basic {L} Energy SVE 4
1 Basic {L} Energy Energy 21 PH
1 Basic {L} Energy EVO 94 PH
1 Basic {L} Energy GRI 168
1 Basic {L} Energy EVS 235
1 Basic {L} Energy Energy 12
1 Basic {L} Energy Energy 21
1 Basic {L} Energy Energy 30
1 Basic {L} Energy Energy 39
1 Basic {L} Energy Energy 4
1 Basic {L} Energy Energy 48
1 Basic {L} Energy ecalt 4
1 Basic {L} Energy BWALT 15
1 Basic {L} Energy CRZ 155
1 Basic {L} Energy BWALT 16
1 Basic {L} Energy GEN 78 PH
1 Basic {L} Energy Energy 39 PH
1 Basic {L} Energy Energy 48 PH
1 Basic {L} Energy EVO 94
1 Basic {L} Energy GEN 78
1 Basic {L} Energy BLW 108
1 Basic {L} Energy XY 135
1 Basic {L} Energy Energy 12 PH

Total Cards: 60


![energies dont combine](https://github.com/BAA-Studios/CastFORM/assets/140216247/4fdaa177-81b2-429c-adb2-750b63e3d2ea)

**Comment by Bratah123** [comment]
Fixed in commit: 4fcb2ed6318f7aef7f6b1c55f2c81236cd1edecc ty!
