### ISSUE TITLE
2024 sheet

### ISSUE THREAD

**Issue by eizdv** [BAA-Studios/CastFORM#21]
Is there a way to update to 2024 format?

**Comment by KOOKIIEStudios** [comment]
I believe you commented the same on our YouTube video for installation/usage instructions; the answer is the same there.

Development team is on hiatus.

Template update was pushed back, awaiting v3 (which includes major toolchain changes). We'll considering updating template for V2 as a stopgap.

**Comment by KOOKIIEStudios** [comment]
Forms updated in [CastFORM v2.0.2](https://github.com/BAA-Studios/CastFORM/releases/tag/v2.0.2); marking issue as resolved.
