### ISSUE TITLE
CastFORM always uses A4 form image

### ISSUE THREAD

**Issue by Gaardus** [BAA-Studios/CastFORM#4]
CastFORM uses the A4 form image when generating PDFs, even if Letter is selected, resulting in misaligned text.
[Sample_A4.pdf](https://github.com/BAA-Studios/CastFORM/files/11992263/Sample_A4.pdf)
[Sample_Letter.pdf](https://github.com/BAA-Studios/CastFORM/files/11992264/Sample_Letter.pdf)

**Comment by KOOKIIEStudios** [comment]
We use A4 for all previews and I'm guessing I probably forgot to account for that on saving to file.
Thanks for that catch!

**Comment by KOOKIIEStudios** [comment]
Resolved as of: 97ae46e
![image](https://github.com/BAA-Studios/CastFORM/assets/25145447/3c00609e-09b8-42f2-892e-4258fe55d042)

Might nudge the coordinates for the `year` field a little before building/bundling 1.2.1

**Comment by KOOKIIEStudios** [comment]
@Gaardus sorry to necro on this issue, but your fork doesn't have the issues page enabled, and your profile so this is the only way I can contact you

I noticed you have the updated forms for the Paldea Expansion, which includes the `PAL` option. Would you be interested in PR-ing your fork?

**Comment by Gaardus** [comment]
Yep!  I had intended to do that, but other things demanded my attention.  Will submit the pull request shortly.
