### ISSUE TITLE
RobotoSlab-Regular.ttf missing from Windows Installer version

### ISSUE THREAD

**Issue by Gaardus** [BAA-Studios/CastFORM#5]
The Windows Installer for CastFORM does not include the file RobotoSlab-Regular.ttf, resulting in formatting issues.
![missingfile](https://github.com/BAA-Studios/CastFORM/assets/56141753/c9714a11-4cd8-4092-8141-ab92fbb21d15)
![formattingissue](https://github.com/BAA-Studios/CastFORM/assets/56141753/1894fd92-ff39-45a6-911e-2d2a6d5f7d73)

**Comment by KOOKIIEStudios** [comment]
Could I check with you which version of the installer this was?

**Comment by Gaardus** [comment]
I experienced this issue with both the 1.1.0 and 1.2.0 installers.

**Comment by KOOKIIEStudios** [comment]
Thank you for your help in identifying the problem.

I have investigated the issue and it's due to a typo in the batch script used for bundling the assets.
I have since updated the installer for 1.2.0
