### ISSUE TITLE
Form doesn't perfectly handle combining regular and Full Art trainer cards

### ISSUE THREAD

**Issue by generalraikou** [BAA-Studios/CastFORM#8]
Hi,

So the code handles regular and secret Power Tablet just fine, but there is something specific to Iono (and perhaps others?), where one exports a decklist from LIVE that includes a regular and FA version of Iono and they are not combined into a single row.

Screenshot below:
![two iono](https://github.com/BAA-Studios/CastFORM/assets/140216247/a41f114d-3572-4444-9022-8cafd831204d)

Decklist provided below for you to recreate issue:  (Note, there is also regular and secret Power Tablet in this list and they are combined just fine.)

Pokémon: 10
1 Eiscue BRS 44
1 Meloetta FST 124
1 Mew VMAX LOR-TG 30
2 Genesect V FST 185
1 Genesect V FST 255
2 Mew VMAX FST 114
1 Mew V FST 250
3 Mew V FST 113
1 Drapion V LOR 182
1 Genesect V FST 254

Trainer: 23
1 Iono PAL 254
1 Switch CRZ 144
1 Escape Rope BST 125
1 Forest Seal Stone SIT 156
1 Choice Belt ASR 211
2 Feather Ball ASR 141
1 Pal Pad SVI 182
2 Lost Vacuum LOR 162
1 Lost City LOR 161
3 Cram-o-matic FST 229
4 Battle VIP Pass FST 225
2 Nest Ball SVI 255
2 Path to the Peak CRE 148
3 Ultra Ball BRS 150
1 Cyllene ASR 201
3 Power Tablet FST 236
3 Elesa's Sparkle FST 233
1 Iono PAL 185 PH
1 Power Tablet FST 281
1 Judge FST 235
1 Avery CRE 187
1 Collapsed Stadium LOR 215
2 Boss's Orders BRS 132

Energy: 2
4 Fusion Strike Energy FST 244
3 Double Turbo Energy BRS 151

Total Cards: 60

**Comment by Bratah123** [comment]
Another edge case I didn't account for, seems like PTCGL appends "PH" to the end of Full Arts/Alt Arts unlike their pokemon counterparts fixed in: 6165c4ecb8fd9022fc4f2aaa00446835da66b752

**Comment by generalraikou** [comment]
BTW, I made a mistake.  The PH is actually added by PTCGL to any reverse holo, not full art/alt arts. This includes any RH back to XY base.  I didn't look at the code, but just making sure you account for it across all card types.

Example deck: 

Pokémon: 11
1 Pelipper PR-SV 22
1 Aipom PGO 56
1 Pelipper PAL 159
1 Aipom PGO 56 PH
1 Bombirdier SVI 219
1 Regieleki VMAX SIT 58
1 Pelipper PAL 159 PH
1 Bidoof XY 106
1 Bidoof XY 106 PH
1 Alolan Rattata SUM 76
1 Alolan Rattata SUM 76 PH

Trainer: 13
1 Ultra Ball SVI 196
1 Giacomo PAL 267
4 Professor's Research SVI 190
1 Boss's Orders PAL 265
4 Electric Generator SVI 170
1 Iono PAL 269
1 Giacomo PAL 182
1 Boss's Orders PAL 248
1 Iono PAL 185 PH
3 Leafy Camo Poncho SIT 160
1 Iono PAL 254
1 Giacomo PAL 252
1 Boss's Orders PAL 172 PH

Energy: 25
1 Basic {L} Energy SVI 257
1 Basic {L} Energy Energy 30
1 Basic {L} Energy Energy 12 PH
1 Basic {L} Energy EVO 94
1 Basic {L} Energy EVO 94 PH
1 Basic {L} Energy Energy 4
1 Basic {L} Energy Energy 39 PH
1 Basic {L} Energy CRZ 155
1 Basic {L} Energy Energy 48 PH
1 Basic {L} Energy GEN 78 PH
1 Basic {L} Energy BWALT 15
4 Basic {L} Energy SVE 4
1 Basic {L} Energy BWALT 16
1 Basic {L} Energy GEN 78
1 Basic {L} Energy Energy 21
1 Basic {L} Energy Energy 12
1 Basic {L} Energy Energy 48
1 Basic {L} Energy BLW 108
1 Basic {L} Energy Energy 21 PH
1 Basic {L} Energy Energy 30 PH
1 Basic {L} Energy ecalt 4
1 Basic {L} Energy XY 135
1 Basic {L} Energy GRI 168
1 Basic {L} Energy Energy 39
1 Basic {L} Energy EVS 235

Total Cards: 60
