### ISSUE TITLE
Age Division box isn't manually or automatically selected

### ISSUE THREAD

**Issue by generalraikou** [BAA-Studios/CastFORM#9]
I'm not always this lazy in life, but I recommend having a triple toggle on the left pane that checks whichever age division checkbox the user chooses.

If you prefer a challenge and dealing with edge cases, you could look to just calculate it based on the DoB and the current date.  (The edge case is where someone will have a birthday that changes their age division between the time they print the form and the tournament date. I think that would be few and far between. so to get around that, you could have a toggle to disable automatically checking the age division boxes.)

**Comment by KOOKIIEStudios** [comment]
Completed as of 3ec577d

![screenshot](https://github.com/BAA-Studios/CastFORM/assets/25145447/01e9491b-a75b-4917-bb67-1e106c77c43a)
